### ISSUE TITLE
Deployment with 2.6.0 fails after upgrading to kamal proxy 0.9.0 with custom ports

### ISSUE THREAD

**Issue by brgmn** [basecamp/kamal#1555]
In some of our projects we run caddy as reverse proxy in front of kamal-proxy on port 8080 and 8443 instead of the default ports 80 and 443. This worked fine until we were forced to upgrade kamal-proxy to 0.9.0 with kamal 2.6.0. Maybe there's a new way to tell kamal that the proxy should be initialized with custom ports. 

In the past we configured the custom ports with a .kamal/proxy/options file on the server: 
`--publish 8080:80 --publish 8443:443 --log-opt max-size=10m`

With kamal-proxy 0.9.0 and kamal 2.6.0 it seems that this option file now leads to broken healthcheck configuration of the app. Instead of using the proxy configuration from the kamal deployment file the kamal deployment mechanism of the configured app seems to fall back to the kamal defaults (port 80 and /up endpoint). This is really strange. 

Kamal proxy gets updated but automatic deployment of the app fails. Website is broken and no easy fix.
<img width="1345" alt="Image" src="https://github.com/user-attachments/assets/3265c369-bb5f-4822-b7b6-4b9c20c8cc48" />

What am I doing wrong? Is there a new way to tell kamal that the proxy should use custom ports? Why does it brake the healthcheck configuration of the deployment. I don't get it :( 

The Proxy configuration in the kamal deployment file looks like this: 
```
proxy:
  ssl: false
  host: testtesttesttest.dev
  app_port: 3000
  healthcheck:
    path: /healthz
    interval: 2
    timeout: 2
```
Why does the app_port in kamal-proxy deploy fall back to port 80?

**Comment by karls** [comment]
I'm seeing the same thing, I think.

I pushed an update to an app that was running on 0.8.4 of kamal-proxy, which told me to upgrade. I did, but then the deployment broke with the same error as above.

Then I tried downgrading kamal to 2.5.3, thinking it would get me back to the 0.8.* version of kamal-proxy, but it's not downgrading automatically and I can't work out how to tell kamal to downgrade the proxy. Is there a way to do that easily?

**Comment by karls** [comment]
OK, part of the above was user error — I was accidentally still using v2.6.0 locally and after downgrading to v2.5.3 properly I *was* able to downgrade to kamal-proxy v0.8.4. However, I still can't deploy, the CI run ends with:

```
2025-05-15T07:49:21.480809081Z + python manage.py collectstatic --no-input
2025-05-15T07:49:28.928678702Z 
2025-05-15T07:49:28.928715383Z 154 static files copied to '/app/static', 456 post-processed.
2025-05-15T07:49:29.547813833Z + python manage.py migrate --no-input
2025-05-15T07:49:32.800990648Z Operations to perform:
2025-05-15T07:49:32.801034448Z   Apply all migrations: admin, appraisals, auth, contenttypes, django_eventstream, sessions, system, transactions
2025-05-15T07:49:32.819647941Z Running migrations:
2025-05-15T07:49:32.819681742Z   No migrations to apply.
  INFO [ecdcb172] Running docker container ls --all --filter name=^lvm-payroll-web-d16f434c8de94fbd732b39aa57f9d255421e53ad$ --quiet | xargs docker inspect --format '{{json .State.Health}}' on xx.xx.xx.xx
 DEBUG [ecdcb172] Command: docker container ls --all --filter name=^lvm-payroll-web-d16f434c8de94fbd732b39aa57f9d255421e53ad$ --quiet | xargs docker inspect --format '{{json .State.Health}}'
 DEBUG [ecdcb172] 	null
  INFO [ecdcb172] Finished in 0.605 seconds with exit status 0 (successful).
 ERROR null
  INFO [9dd1600d] Running docker container ls --all --filter name=^lvm-payroll-web-d16f434c8de94fbd732b39aa57f9d255421e53ad$ --quiet | xargs docker stop on xx.xx.xx.xx
 DEBUG [9dd1600d] Command: docker container ls --all --filter name=^lvm-payroll-web-d16f434c8de94fbd732b39aa57f9d255421e53ad$ --quiet | xargs docker stop
 DEBUG [9dd1600d] 	ec239b3845b4
  INFO [9dd1600d] Finished in 10.783 seconds with exit status 0 (successful).
Releasing the deploy lock...
 DEBUG [b82c5eee] Running /usr/bin/env rm .kamal/lock-lvm-payroll/details && rm -r .kamal/lock-lvm-payroll on xx.xx.xx.xx
 DEBUG [b82c5eee] Command: /usr/bin/env rm .kamal/lock-lvm-payroll/details && rm -r .kamal/lock-lvm-payroll
 DEBUG [b82c5eee] Finished in 0.562 seconds with exit status 0 (successful).
  Finished all in 71.6 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host xx.xx.xx.xx: docker exit status: 1
docker stdout: Nothing written
docker stderr: Error: target failed to become healthy within configured timeout (10s)

/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/command.rb:97:in `exit_status='
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/netssh.rb:185:in `execute_command'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/abstract.rb:147:in `block in create_command_and_execute'
<internal:kernel>:90:in `tap'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/abstract.rb:147:in `create_command_and_execute'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/abstract.rb:80:in `execute'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app/boot.rb:3:in `execute'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app/boot.rb:57:in `start_new_version'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app/boot.rb:20:in `run'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app.rb:25:in `block (5 levels) in boot'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app.rb:24:in `each'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/cli/app.rb:24:in `block (4 levels) in boot'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/sshkit-1.24.0/lib/sshkit/backends/abstract.rb:31:in `run'
/opt/hostedtoolcache/Ruby/3.2.8/x64/lib/ruby/gems/3.2.0/gems/kamal-2.5.3/lib/kamal/sshkit_with_ext.rb:118:in `block (2 levels) in execute'
Error: Process completed with exit code 1.
```

Here's a section from my deploy.yml:

```yml
deploy_timeout: 10

# Deploy to these servers.
servers:
  web:
    hosts:
      - xxx

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# Set ssl: false if using something like Cloudflare to terminate SSL (but keep host!).
proxy:
  ssl: true
  app_port: 8000
  host: xxx
  forward_headers: true
  healthcheck:
    path: /up/
```

And the relevant section from GHA workflow file:

```yml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.2"

      - name: Install Kamal
        run: gem install kamal -v 2.5.3

      - name: Deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
        run: kamal deploy --verbose
```

**Comment by brgmn** [comment]
@karls You can put an image_version file into /root/.kamal/proxy folder with the kamal-proxy version you want to use (e.g. v0.8.7) on your server. Unfortunately downgrading kamal-proxy didn't fix the error for me. Something seems to be broken in kamal 2.6.0. I'm also wondering what the new apps-config folder under /root/.kamal/proxy is used for. Can't find something about it in the documentation.

**Comment by karls** [comment]
I managed to downgrade by installing 2.5.3 locally and running `kamal proxy reboot`, which downgraded kamal-proxy on the server. Then downgraded kamal in CI as well, but this still doesn't seem to work.

**Comment by djmb** [comment]
@brgmn - the issue appears to be related to the app_port setting somehow, but I'm not sure how this would happen - the port used in the [kamal-proxy deploy command](https://github.com/basecamp/kamal/blob/f62c1a50c49ecb8fc858841ebeecb1bbf259439a/lib/kamal/configuration/proxy.rb#L53) should be read from the [proxy config](https://github.com/basecamp/kamal/blob/f62c1a50c49ecb8fc858841ebeecb1bbf259439a/lib/kamal/configuration/proxy.rb#L18).

This doesn't seem related to kamal-proxy 0.9.0 though, looks like somehow Kamal is passing the proxy the wrong port.

- Does it still use the wrong port if you run `kamal proxy deploy`?
- Do you have multiple destinations or roles in your config?

**Comment by brgmn** [comment]
@djmb Thanks for your help! 

"Does it still use the wrong port if you run kamal proxy deploy?"
-> yes. app_port 3000 is defined in the kamal deployment. 80 is used. Deployment fails

"Do you have multiple destinations or roles in your config?"
-> only one web and one job role. 

Looks like that: 

```
servers:
  web:
    hosts:
      - bc-web1
  job:
    proxy: false
    hosts:
      - bc-web1
    cmd: php artisan queue:work
    labels:
      type: "worker"
```

When I downgrade kamal to 2.5.3 deployment works agin (even with kamal-proxy 0.9.0/0.9.1)

**Comment by brgmn** [comment]
@djmb UPDATE: I just saw https://github.com/basecamp/kamal/issues/1556 and tested to move my proxy configuration under the app role and it works now! The global proxy configuration in a kamal deployment seems to have no effect anymore - is this intended? If yes, this is definitely a breaking change and should lead to a faling deployment with a notice (like with other outdated options).

**Comment by djmb** [comment]
Oh thanks, that's helpful. You shouldn't need to move the proxy configuration under the app so I'll see if I can work out what's going on.

You also shouldn't need the `proxy: false` for the job configuration, by default the proxy is only enabled for the primary role (web). Does it work without the `proxy: false` and with the proxy config at the root?

**Comment by brgmn** [comment]
@djmb  

> Does it work without the proxy: false and with the proxy config at the root?

Unfortunately no. It really seems that the global proxy configuration is broken in kamal 2.6.0

**Comment by djmb** [comment]
I still can't reproduce this - maybe if we could see you full config (removing anything sensitive) that might be useful. Maybe there's something important in there I'm missing.

This would happen if somehow @raw_config.key?(:proxy) returned a falsey value [here](https://github.com/basecamp/kamal/blob/128294672db9b2566595912bc299ae18403895f8/lib/kamal/configuration.rb#L66) and that check is new in Kamal 2.6.0. 

I don't see why that would happen, but I'm changing it in https://github.com/basecamp/kamal/pull/1559 so maybe that will help. Still even if it does that's not very satisfactory.

**Comment by marekls** [comment]
@djmb 
The current main branch started working for me:
In proxy logs, I noticed that the host wasn't passed in 2.6.0:
deploy config is the same for each deploy
```
2.5.3 + 0.8.4 (working):
{"time":"2025-05-15T06:39:21.956110659Z","level":"INFO","msg":"Deploying","service":"my-service","hosts":["my.domain.com"],"target":"b8692ab9b032:80","tls":true}

2.6.0 + 0.9.0 (not working):
{"time":"2025-05-15T14:06:15.554882768Z","level":"INFO","msg":"Deploying","service":"my-service","targets":["b8692ab9b032:80"],"hosts":[""],"paths":["/"],"tls":false}

2.5.3 + 0.9.0 (working):
{"time":"2025-05-15T14:11:35.926179712Z","level":"INFO","msg":"Deploying","service":"my-service","targets":["5882c712bbf7:80"],"hosts":["my.domain.com"],"paths":["/"],"tls":true}

master + 0.9.0 (working):
{"time":"2025-05-15T14:14:21.839145337Z","level":"INFO","msg":"Deploying","service":"my-service","targets":["996cb5accd59:80"],"hosts":["my.domain.com"],"paths":["/"],"tls":true}
```

**Comment by djmb** [comment]
Thanks @marekls - seems like #1559 might have fixed it then? I've just released that in Kamal 2.6.1, so would be good to know if everything is working ok there.

If it is that doesn't explain what the issue was though. Maybe related to the version of activesupport or something like that?

**Comment by marekls** [comment]
2.6.1 is working fine with my minimal setup:
```
servers:
  - x.x.x.x

proxy:
  ssl: true
  host: my.domain.com
```

**Comment by karls** [comment]
Can confirm here too — everything works with kamal v2.6.1 and kamal-proxy v0.9.0.

Thank you for reacting and fixing quickly!
