### ISSUE TITLE
Cannot use Kamal local docker registry on macOS when deploying a Rails app

### ISSUE THREAD

**Issue by jeromedalbert** [basecamp/kamal#1674]
After https://github.com/basecamp/kamal/pull/1355 got merged and released, I tried deploying a Rails app using the local docker registry with Kamal configured the same way as this pending Rails PR from DHH: https://github.com/rails/rails/pull/55934. I am on macOS. But when I run `bin/kamal setup`, I eventually get the following error:

```
ERROR (SSHKit::Command::Failed): Exception while executing on host 5.78.64.88: docker exit status: 1
docker stdout: Nothing written
docker stderr: Error response from daemon: Get "http://localhost:5555/v2/": dial tcp [::1]:5555: connect: connection refused
```

### Steps to repro

Clone the following repro Rails app, and follow its README instructions: https://github.com/jeromedalbert/rails-55934. 

### Additional information

I am on macOS, deploying a Rails 8.1 RC1 app, with the latest Docker Desktop 4.48.0, and the latest Kamal 2.8.0.

**Comment by brunoprietog** [comment]
I can confirm from a primary source that it works on Mac. It's probably something else that's not working on your end.

**Comment by adrienpoly** [comment]
I tried also to use it a I get a similar error 

here is a public build if this can help https://github.com/rubyevents/rubyevents/actions/runs/18659102655/job/53195241858

In my can the kamal server was already setup with an external Docker registry. Not sure if in such cases I would need to anything specific. I did try to run kamal setup but I had the same error.

Looking at the logs it seems we can push the image but we are not able to pull it ?

**Comment by djmb** [comment]
I think this looks like a timing issue - we set up port forwarding so the app servers can access the registry as localhost. It should confirm the ports are all up before doing the docker pull. 

I'm working on a fix now

**Comment by djmb** [comment]
@jeromedalbert - I've released Kamal 2.8.1 with that fix.

**Comment by adrienpoly** [comment]
Thanks I have tested 2.8.1.

I can now deploy from my [CI task](https://github.com/rubyevents/rubyevents/actions/runs/18674015904/job/53240624900) but I am still getting a similar error when I try to deploy from my Mac 

```
#24 pushing layers done
#24 ERROR: failed to push localhost:5555/rubyvideo_staging:89cab782e8922335a9d291bac0d5239104e9e646: failed to do request: Head "http://localhost:5555/v2/rubyvideo_staging/blobs/sha256:642c8d598515e43779219de64dc280874a6c8baedb9ca1673d97dea535341474": dial tcp [::1]:5555: connect: connection refused
------
 > exporting to image:
------
ERROR: failed to solve: failed to push localhost:5555/rubyvideo_staging:89cab782e8922335a9d291bac0d5239104e9e646: failed to do request: Head "http://localhost:5555/v2/rubyvideo_staging/blobs/sha256:642c8d598515e43779219de64dc280874a6c8baedb9ca1673d97dea535341474": dial tcp [::1]:5555: connect: connection refused

View build details: docker-desktop://dashboard/build/kamal-remote-ssh---root-138-199-198-123/kamal-remote-ssh---root-138-199-198-1230/n2owed6g4a21l40eodxi5h49w
docker stderr: Nothing written
```

I am trying to find out what is the difference between both envs... Both have ssh access to the server, I have the latest version of docker desktop running 
 
@jeromedalbert are you now able to deploy from your mac ?

**Comment by jeromedalbert** [comment]
@djmb I just tried 2.8.1 and that fixed it, thanks for such a quick fix and version bump!

@adrienpoly Your issue has a slightly different error message that happens during the image build, when pushing from your local to your local registry. My issue was happening after the image build, when the remote server was trying to pull from my local registry. I am not a Docker expert, but it may be worth checking if you get an OK response when doing `curl -I http://localhost:5555/v2/`.

**Comment by adrienpoly** [comment]
I think I’ve found part of the issue.

I was testing this on our staging VPS, which also happens to serve as our remote builder. Since GitHub Actions can be quite slow when building ARM images, we use a remote builder and to keep costs down, that remote builder is the same machine as our staging VPS.

It looks like there’s a conflict between the local registry and the remote builder when both run on the same host. What’s strange is that this setup works fine when triggered from CI, but fails when deploying from my Mac.

If I remove the remote builder configuration, I can deploy from my Mac without any issues.

**Comment by djmb** [comment]
@adrienpoly - when you deploy from an amd64 hosts to an amd64 host, then it will do a local build even if a remote builder is set up.  The remote builder will only be used from arm64 hosts. You need to set `local: false` to force it to always build remotely.

So I think what you are seeing is that the local registry just doesn't work with a remote builder. We maybe need to set up the port forwarding there as well, though that would be tricky if you are doing concurrent builds and they both try to set up the forwarding. I'll take a look!

**Comment by djmb** [comment]
@adrienpoly - I think https://github.com/basecamp/kamal/pull/1679 should fix this. Could you confirm if it works for you?
