### ISSUE TITLE
Remote builder failing when using "Using remote builder for native multi-arch"

### ISSUE THREAD

**Issue by hundredwatt** [basecamp/kamal#783]
## Summary

* I attempted my first multi-arch build using a local builder for arm64 and a remote builder for amd64
* The local builder succeeded and pushed `--platform arm64` images to my registry
* The remote builder started up and attempted to pull an image with the current tag, but failed because no image with `--platform amd64`
* SSH to the remote builder is working and it appears to be configured correctly (docker installed and logged in to my registry)

## Details

config/deploy.yml:
```
 builder:
  local:
    arch: arm64
    host: unix:///Users/<%= `whoami`.strip %>/.docker/run/docker.sock
  remote:
    arch: amd64
    host: ssh://root@<ip-address>
```

Error from remote builder:
```
docker stderr: no matching manifest for linux/amd64 in the manifest list entries

```

Logs:
```
$ kamal deploy

<snip>

# Local builder finishes:
 DEBUG [71961adc] 	#25 pushing manifest for registry.digitalocean.com/app:latest@sha256:e63b66577b22ce8f19040d0da1b9698dd8e0d3ed717dfa5e2f80ba4adf5a2f9b
 DEBUG [71961adc] 	#25 pushing manifest for registry.digitalocean.com/app:latest@sha256:e63b66577b22ce8f19040d0da1b9698dd8e0d3ed717dfa5e2f80ba4adf5a2f9b 0.4s done
 DEBUG [71961adc] 	#25 DONE 78.0s

# Remote builder starts:

 INFO [c69e957a] Running docker pull registry.digitalocean.com/app:03c7365dd5f1c8f5e11a582c4d9dde961f83a4c4_uncommitted_113fe9f1704416cc on <ip-address>
Releasing the deploy lock...
  Finished all in 182.5 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host <ip-address>: docker exit status: 1
docker stdout: 03c7365dd5f1c8f5e11a582c4d9dde961f83a4c4_uncommitted_113fe9f1704416cc: Pulling from app
docker stderr: no matching manifest for linux/amd64 in the manifest list entries
```

The host at <ip-address> is authenticated to registry.digitalocean.com:
```
root@<ip-address>:~# cat .docker/config.json
{
	"auths": {
		"registry.digitalocean.com": {}
	}
}
```

## Status

Posting here to see if anyone knows how to fix, otherwise I'll try to investigate further when I get time

**Comment by dhh** [comment]
Kamal is designed to EITHER use local or remote building. It's not designed for using both to produce a single multi-arch image. I don't even think that's possible.

**Comment by hundredwatt** [comment]
The first builder example in the docs uses both:

<img width="1584" alt="image" src="https://github.com/basecamp/kamal/assets/91577/4b5496d2-3f27-4d9a-a07a-e268069f387a">

**Comment by dhh** [comment]
Lol. There goes my memory. cc @djmb

**Comment by djmb** [comment]
@hundredwatt - that error is not coming from the remote builder, but from the host you are deploying to. It's pulling the image and complaining that it's not built for `linux/amd64`.

Your config should be right for building a mutli-platform image though!

Could you try removing the builder `kamal build remove` and then running the build again? If it doesn't work, could you post the `docker context` and `docker buildx` commands that it runs?

**Comment by kaka-ruto** [comment]
I am getting the same errors as above

This is my builder section
```
builder:
  args:
    RUBY_VERSION: <%= ruby_version %>
    RAILS_ENV: <%= rails_env %>
  remote:
    arch: amd64
    host: <%= ssh_url %>
```

I have ran `kamal build remove`

Here is my `docker context ls` (I am using Orbstack for my docker, I wonder if that's the weakpoint)

```
orbstack *                                OrbStack                                              unix:///Users/kaka/.orbstack/run/docker.sock
```

Here is the last trace of my error
```
Running docker image rm --force ghcr.io/name/name_staging:45eea3075e64ec33e842afb99e600f30810bdbb2 on 135.181.251.34
  INFO [6623a9a4] Finished in 0.316 seconds with exit status 0 (successful).
  INFO [930dea80] Running docker pull ghcr.io/name/name_staging:45eea3075e64ec33e842afb99e600f30810bdbb2 on 135.181.251.34
  Finished all in 23.3 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 135.181.251.34: docker exit status: 1
docker stdout: 45eea3075e64ec33e842afb99e600f30810bdbb2: Pulling from name/name_staging
docker stderr: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by djmb** [comment]
@kaka-ruto - could you post the `docker buildx build` command from the Kamal output?

**Comment by hundredwatt** [comment]
@djmb I updated to Kamal 1.8.2 and ran `kamal build remove`, but am still getting the error.

Today, I noticed it never runs anything on the remote builder... maybe that's the issue 🧐

Notice in the logs below it only runs `build` on localhost for arm64... I don't see any commands on the amd64 builder or for amd64

```
$ docker context ls                                                                                                                      [main]
NAME                                  TYPE                DESCRIPTION                                       DOCKER ENDPOINT                               KUBERNETES ENDPOINT   ORCHESTRATOR
default                               moby                Current DOCKER_HOST based configuration           unix:///var/run/docker.sock
desktop-linux *                       moby                Docker Desktop                                    unix:///Users/jason/.docker/run/docker.sock
kamal-myapp-multiarch-remote-amd64   moby                kamal-myapp-multiarch-remote amd64 native host   ssh://root@<BUILDER IP>
kamal-myapp-multiarch-remote-arm64   moby                kamal-myapp-multiarch-remote arm64 native host   unix:///Users/jason/.docker/run/docker.sock
```

Logs:
```
$ kamal deploy
....
  INFO [247bf057] Running docker buildx build --push --platform linux/arm64 --builder kamal-myapp-multiarch-remote -t registry.digitalocean.com/myapp-demo/myapp:d2ee978f9db10125f21112707d744c5ee712ade2 -t registry.digitalocean.com/myapp-demo/myapp:latest --label service="myapp" --secret id="DO_REGISTRY_API_TOKEN" --file Dockerfile . as jason@localhost
 DEBUG [247bf057] Command: docker buildx build --push --platform linux/arm64 --builder kamal-myapp-multiarch-remote -t registry.digitalocean.com/myapp-demo/myapp:d2ee978f9db10125f21112707d744c5ee712ade2 -t registry.digitalocean.com/myapp-demo/myapp:latest --label service="myapp" --secret id="DO_REGISTRY_API_TOKEN" --file Dockerfile .
 DEBUG [247bf057] 	#0 building with "kamal-myapp-multiarch-remote" instance using docker-container driver
...
 DEBUG [247bf057] 	#29 DONE 3.8s
  INFO [247bf057] Finished in 5.416 seconds with exit status 0 (successful).
  INFO [1a610493] Running docker image rm --force registry.digitalocean.com/myapp-demo/myapp:d2ee978f9db10125f21112707d744c5ee712ade2 on 209.38.148.231
  INFO [1a610493] Finished in 0.207 seconds with exit status 0 (successful).
  INFO [77e61f23] Running docker pull registry.digitalocean.com/myapp-demo/myapp:d2ee978f9db10125f21112707d744c5ee712ade2 on 209.38.148.231
  Finished all in 10.3 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 209.38.148.231: docker exit status: 1
docker stdout: d2ee978f9db10125f21112707d744c5ee712ade2: Pulling from myapp-demo/myapp
docker stderr: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by kaka-ruto** [comment]
@djmb this is the output of `docker builds build` when I `kamal deploy` on my local Apple Silicon laptop with the above config

```
[c1b2c002] Running docker buildx build --push -t ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0 -t ghcr.io/autohaven/autohaven_staging:latest-staging --cache-to type=gha --cache-from type=gha --label service="autohaven_staging" --build-arg [REDACTED] --build-arg [REDACTED] --file Dockerfile . as kaka@localhost
 DEBUG [c1b2c002] Command: docker buildx build --push -t ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0 -t ghcr.io/autohaven/autohaven_staging:latest-staging --cache-to type=gha --cache-from type=gha --label service="autohaven_staging" --build-arg [REDACTED] --build-arg [REDACTED] --file Dockerfile .
 DEBUG [c1b2c002]       #0 building with "kamal-autohaven_staging-native-cached" instance using docker-container driver
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #1 [internal] load build definition from Dockerfile
 DEBUG [c1b2c002]       #1 transferring dockerfile: 2.84kB done
 DEBUG [c1b2c002]       #1 DONE 0.0s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #2 resolve image config for docker-image://docker.io/docker/dockerfile:1
 DEBUG [c1b2c002]       #2 DONE 1.1s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #3 docker-image://docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28
 DEBUG [c1b2c002]       #3 resolve docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28 0.0s done
 DEBUG [c1b2c002]       #3 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #4 [internal] load metadata for registry.docker.com/library/ruby:3.3.4-slim
 DEBUG [c1b2c002]       #4 DONE 0.9s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #5 [internal] load .dockerignore
 DEBUG [c1b2c002]       #5 transferring context: 839B done
 DEBUG [c1b2c002]       #5 DONE 0.0s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #6 [internal] load build context
 DEBUG [c1b2c002]       #6 DONE 0.0s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #7 [base 1/2] FROM registry.docker.com/library/ruby:3.3.4-slim@sha256:7bb0e1e46378217ce0775845f6d64b039c56d2890bc715536e6687ab13fe2930
 DEBUG [c1b2c002]       #7 resolve registry.docker.com/library/ruby:3.3.4-slim@sha256:7bb0e1e46378217ce0775845f6d64b039c56d2890bc715536e6687ab13fe2930 0.0s done
 DEBUG [c1b2c002]       #7 DONE 0.0s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #6 [internal] load build context
 DEBUG [c1b2c002]       #6 transferring context: 157.71kB 0.1s done
 DEBUG [c1b2c002]       #6 DONE 0.1s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #8 [build  5/11] COPY ./config/jumpstart.yml* ./config/jumpstart.yml
 DEBUG [c1b2c002]       #8 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #9 [build 11/11] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
 DEBUG [c1b2c002]       #9 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #10 [build 10/11] RUN bundle exec bootsnap precompile app/ lib/
 DEBUG [c1b2c002]       #10 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #11 [stage-2 2/4] COPY --from=build /usr/local/bundle /usr/local/bundle
 DEBUG [c1b2c002]       #11 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #12 [stage-2 1/4] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y curl libvips postgresql-client &&     apt-get clean &&     rm -rf /var/lib/apt/lists /var/cache/apt/archives
 DEBUG [c1b2c002]       #12 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #13 [base 2/2] WORKDIR /rails
 DEBUG [c1b2c002]       #13 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #14 [stage-2 3/4] COPY --from=build /rails /rails
 DEBUG [c1b2c002]       #14 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #15 [build  2/11] RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ &&     /tmp/node-build-master/bin/node-build "20.15.1" /usr/local/node &&     npm install -g yarn@1.22.21 &&     rm -rf /tmp/node-build-master
 DEBUG [c1b2c002]       #15 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #16 [build  6/11] RUN bundle install &&     rm -rf ~/.bundle/ "/usr/local/bundle"/ruby/*/cache "/usr/local/bundle"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile
 DEBUG [c1b2c002]       #16 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #17 [build  1/11] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y build-essential curl git libpq-dev node-gyp pkg-config python-is-python3 imagemagick libvips libvips-dev libvips-tools poppler-utils libjemalloc2
 DEBUG [c1b2c002]       #17 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #18 [build  3/11] COPY Gemfile Gemfile.jumpstart Gemfile.lock ./.ruby-version ./
 DEBUG [c1b2c002]       #18 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #19 [build  8/11] RUN yarn install --frozen-lockfile
 DEBUG [c1b2c002]       #19 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #20 [build  9/11] COPY . .
 DEBUG [c1b2c002]       #20 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #21 [build  7/11] COPY package.json yarn.lock ./
 DEBUG [c1b2c002]       #21 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #22 [build  4/11] COPY ./lib/jumpstart/ ./lib/jumpstart/
 DEBUG [c1b2c002]       #22 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #23 [stage-2 4/4] RUN useradd rails --create-home --shell /bin/bash &&     chown -R rails:rails db log storage tmp
 DEBUG [c1b2c002]       #23 CACHED
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #24 exporting to image
 DEBUG [c1b2c002]       #24 exporting layers done
 DEBUG [c1b2c002]       #24 exporting manifest sha256:2b278e3315825d9043a319a9473a9c3fcfaba22c14c7b94e1f8291ab26db8b58 done
 DEBUG [c1b2c002]       #24 exporting config sha256:6b5c3bcb304c96a1c37a6db1e5936cec94bc668a7a394d18e956f09d0223466b done
 DEBUG [c1b2c002]       #24 exporting attestation manifest sha256:f932f8d241836e279ac757beb6fc09c622059d8301da88bbb1445ea76e2ab122 0.0s done
 DEBUG [c1b2c002]       #24 exporting manifest list sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570
 DEBUG [c1b2c002]       #24 exporting manifest list sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570 0.0s done
 DEBUG [c1b2c002]       #24 pushing layers
 DEBUG [c1b2c002]       #24 ...
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #25 [auth] autohaven/autohaven_staging:pull,push token for ghcr.io
 DEBUG [c1b2c002]       #25 DONE 0.0s
 DEBUG [c1b2c002]
 DEBUG [c1b2c002]       #24 exporting to image
 DEBUG [c1b2c002]       #24 pushing layers 1.2s done
 DEBUG [c1b2c002]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0@sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570
 DEBUG [c1b2c002]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0@sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570 1.1s done
 DEBUG [c1b2c002]       #24 pushing layers 0.5s done
 DEBUG [c1b2c002]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:latest-staging@sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570
 DEBUG [c1b2c002]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:latest-staging@sha256:32273fb3f13a9063914810d3094066217419429c30deb486f903abad9c0fd570 0.8s done
 DEBUG [c1b2c002]       #24 DONE 3.6s
  INFO [c1b2c002] Finished in 6.505 seconds with exit status 0 (successful).
  INFO [be53991e] Running docker image rm --force ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0 on 135.181.251.34
  INFO [be53991e] Finished in 0.256 seconds with exit status 0 (successful).
  INFO [5b8d3c6e] Running docker pull ghcr.io/autohaven/autohaven_staging:106764f1b53e2285dcd2311580f752b0b314fbe0 on 135.181.251.34
  Finished all in 13.5 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host <ip>: docker exit status: 1
docker stdout: 106764f1b53e2285dcd2311580f752b0b314fbe0: Pulling from autohaven/autohaven_staging
docker stderr: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by djmb** [comment]
Ok, I think this one should be fixed now by https://github.com/basecamp/kamal/pull/922. That's been release in v1.8.3.

**Comment by hundredwatt** [comment]
updated to 1.8.3 and it's working for me! 🎉

**Comment by kaka-ruto** [comment]
Excited for the fix but I'm, not sure what I'm doing wrong as I'm still getting the same error. For surety, this is my config

```
builder:
  args:
    RUBY_VERSION: <%= ruby_version %>
    RAILS_ENV: <%= rails_env %>
  remote:
    arch: amd64
    host: <%= ssh_url %>
  local:
    arch: arm64
    host: unix:///Users/<%= `whoami`.strip %>/.docker/run/docker.sock
  cache:
    type: gha
```
I have updated to v 1.8.3 and ran `kamal build remove -d staging` and `kamal deploy -d staging` (as I am testing on staging)

And this is the latest output
```
Running docker buildx build --push -t ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a -t ghcr.io/autohaven/autohaven_staging:latest-staging --cache-to type=gha --cache-from type=gha --label service="autohaven_staging" --build-arg [REDACTED] --build-arg [REDACTED] --file Dockerfile . as kaka@localhost
 DEBUG [06061d26] Command: docker buildx build --push -t ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a -t ghcr.io/autohaven/autohaven_staging:latest-staging --cache-to type=gha --cache-from type=gha --label service="autohaven_staging" --build-arg [REDACTED] --build-arg [REDACTED] --file Dockerfile .
 DEBUG [06061d26]       #0 building with "kamal-autohaven_staging-native-cached" instance using docker-container driver
 DEBUG [06061d26]
 DEBUG [06061d26]       #1 [internal] load build definition from Dockerfile
 DEBUG [06061d26]       #1 transferring dockerfile: 2.84kB done
 DEBUG [06061d26]       #1 DONE 0.0s
 DEBUG [06061d26]
 DEBUG [06061d26]       #2 resolve image config for docker-image://docker.io/docker/dockerfile:1
 DEBUG [06061d26]       #2 DONE 3.2s
 DEBUG [06061d26]
 DEBUG [06061d26]       #3 docker-image://docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28
 DEBUG [06061d26]       #3 resolve docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28 0.0s done
 DEBUG [06061d26]       #3 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #4 [internal] load metadata for registry.docker.com/library/ruby:3.3.4-slim
 DEBUG [06061d26]       #4 DONE 2.5s
 DEBUG [06061d26]
 DEBUG [06061d26]       #5 [internal] load .dockerignore
 DEBUG [06061d26]       #5 transferring context: 839B done
 DEBUG [06061d26]       #5 DONE 0.0s
 DEBUG [06061d26]
 DEBUG [06061d26]       #6 [internal] load build context
 DEBUG [06061d26]       #6 DONE 0.0s
 DEBUG [06061d26]
 DEBUG [06061d26]       #7 [base 1/2] FROM registry.docker.com/library/ruby:3.3.4-slim@sha256:7bb0e1e46378217ce0775845f6d64b039c56d2890bc715536e6687ab13fe2930
 DEBUG [06061d26]       #7 resolve registry.docker.com/library/ruby:3.3.4-slim@sha256:7bb0e1e46378217ce0775845f6d64b039c56d2890bc715536e6687ab13fe2930
 DEBUG [06061d26]       #7 resolve registry.docker.com/library/ruby:3.3.4-slim@sha256:7bb0e1e46378217ce0775845f6d64b039c56d2890bc715536e6687ab13fe2930 0.0s done
 DEBUG [06061d26]       #7 DONE 0.0s
 DEBUG [06061d26]
 DEBUG [06061d26]       #6 [internal] load build context
 DEBUG [06061d26]       #6 transferring context: 161.80kB 0.1s done
 DEBUG [06061d26]       #6 DONE 0.1s
 DEBUG [06061d26]
 DEBUG [06061d26]       #8 [build  7/11] COPY package.json yarn.lock ./
 DEBUG [06061d26]       #8 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #9 [stage-2 2/4] COPY --from=build /usr/local/bundle /usr/local/bundle
 DEBUG [06061d26]       #9 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #10 [build  3/11] COPY Gemfile Gemfile.jumpstart Gemfile.lock ./.ruby-version ./
 DEBUG [06061d26]       #10 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #11 [build  2/11] RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ &&     /tmp/node-build-master/bin/node-build "20.15.1" /usr/local/node &&     npm install -g yarn@1.22.21 &&     rm -rf /tmp/node-build-master
 DEBUG [06061d26]       #11 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #12 [build 11/11] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
 DEBUG [06061d26]       #12 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #13 [build  1/11] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y build-essential curl git libpq-dev node-gyp pkg-config python-is-python3 imagemagick libvips libvips-dev libvips-tools poppler-utils libjemalloc2
 DEBUG [06061d26]       #13 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #14 [build  8/11] RUN yarn install --frozen-lockfile
 DEBUG [06061d26]       #14 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #15 [build  4/11] COPY ./lib/jumpstart/ ./lib/jumpstart/
 DEBUG [06061d26]       #15 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #16 [build  6/11] RUN bundle install &&     rm -rf ~/.bundle/ "/usr/local/bundle"/ruby/*/cache "/usr/local/bundle"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile
 DEBUG [06061d26]       #16 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #17 [base 2/2] WORKDIR /rails
 DEBUG [06061d26]       #17 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #18 [stage-2 3/4] COPY --from=build /rails /rails
 DEBUG [06061d26]       #18 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #19 [build  9/11] COPY . .
 DEBUG [06061d26]       #19 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #20 [stage-2 1/4] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y curl libvips postgresql-client &&     apt-get clean &&     rm -rf /var/lib/apt/lists /var/cache/apt/archives
 DEBUG [06061d26]       #20 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #21 [build  5/11] COPY ./config/jumpstart.yml* ./config/jumpstart.yml
 DEBUG [06061d26]       #21 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #22 [build 10/11] RUN bundle exec bootsnap precompile app/ lib/
 DEBUG [06061d26]       #22 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #23 [stage-2 4/4] RUN useradd rails --create-home --shell /bin/bash &&     chown -R rails:rails db log storage tmp
 DEBUG [06061d26]       #23 CACHED
 DEBUG [06061d26]
 DEBUG [06061d26]       #24 exporting to image
 DEBUG [06061d26]       #24 exporting layers done
 DEBUG [06061d26]       #24 exporting manifest sha256:644de04ff83cb4934f9ef78bea1657509c008c9f8e67822554ab3db1d512c8c1 done
 DEBUG [06061d26]       #24 exporting config sha256:58a5fc8f07cf633b9dbc830dd03c70807535b9ecaf204943da4beab3393c5fb2 done
 DEBUG [06061d26]       #24 exporting attestation manifest sha256:a349bcab0721a393a3b826680ce3f084a32a14d0f86489577f496b2c404f75ec 0.0s done
 DEBUG [06061d26]       #24 exporting manifest list sha256:8173d3bbab3796c1f150b27b50291fcb2c6ae4c4224c16448aa04212eb4ef748 done
 DEBUG [06061d26]       #24 pushing layers
 DEBUG [06061d26]       #24 ...
 DEBUG [06061d26]
 DEBUG [06061d26]       #25 [auth] autohaven/autohaven_staging:pull,push token for ghcr.io
 DEBUG [06061d26]       #25 DONE 0.0s
 DEBUG [06061d26]
 DEBUG [06061d26]       #24 exporting to image
 DEBUG [06061d26]       #24 pushing layers 1.2s done
 DEBUG [06061d26]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a@sha256:8173d3bbab3796c1f150b27b50291fcb2c6ae4c4224c16448aa04212eb4ef748
 DEBUG [06061d26]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a@sha256:8173d3bbab3796c1f150b27b50291fcb2c6ae4c4224c16448aa04212eb4ef748 1.1s done
 DEBUG [06061d26]       #24 pushing layers 0.4s done
 DEBUG [06061d26]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:latest-staging@sha256:8173d3bbab3796c1f150b27b50291fcb2c6ae4c4224c16448aa04212eb4ef748
 DEBUG [06061d26]       #24 pushing manifest for ghcr.io/autohaven/autohaven_staging:latest-staging@sha256:8173d3bbab3796c1f150b27b50291fcb2c6ae4c4224c16448aa04212eb4ef748 0.7s done
 DEBUG [06061d26]       #24 DONE 3.5s
  INFO [06061d26] Finished in 9.884 seconds with exit status 0 (successful).
  INFO [d8bf5514] Running docker image rm --force ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a on 135.181.251.34
  INFO [d8bf5514] Finished in 0.252 seconds with exit status 0 (successful).
  INFO [27e6bae7] Running docker pull ghcr.io/autohaven/autohaven_staging:65c172637a761abfaa9b669a30e0e6d7999af88a on 135.181.251.34
  Finished all in 17.0 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 135.181.251.34: docker exit status: 1
docker stdout: 65c172637a761abfaa9b669a30e0e6d7999af88a: Pulling from autohaven/autohaven_staging
docker stderr: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by ekuzovlev** [comment]
It's work for me. Mac M1
```
builder:
  arch:
    - amd64
    - arm64
  remote: ssh://user@xxx.xxx.xxx.xxx
```

**Comment by serv** [comment]
@ekuzovlev , this worked for me on Mac M1 as well.

Can you help explain what this config means?

**Comment by Adham2023** [comment]
Hello everyone, why it might not working in my case: 

```bash
#28 [linux/amd64 build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
#28 1.514 bin/rails aborted!
#28 1.514 Command failed with SIGILL (signal 4): /usr/local/bundle/ruby/3.3.0/gems/tailwindcss-ruby-4.0.1-x86_64-linux-gnu/exe/x86_64-linux-gnu/tailwindcss
#28 1.524
#28 1.524 Tasks: TOP => assets:precompile => tailwindcss:build
#28 1.524 (See full trace by running task with --trace)
#28 ERROR: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1
------
 > [linux/amd64 build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
1.514 bin/rails aborted!
1.514 Command failed with SIGILL (signal 4): /usr/local/bundle/ruby/3.3.0/gems/tailwindcss-ruby-4.0.1-x86_64-linux-gnu/exe/x86_64-linux-gnu/tailwindcss
1.524
1.524 Tasks: TOP => assets:precompile => tailwindcss:build
1.524 (See full trace by running task with --trace)
------
Dockerfile:49
--------------------
  47 |
  48 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  49 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  50 |     # RUN SECRET_KEY_BASE_DUMMY=1 ./bin/bundle exec rails assets:precompile
  51 |
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1
```
